from .sph2color      import *
from .color2normal   import *
from .color2position import *
from .color2sph      import *
from .index2label    import *
from .index2onehot   import *
from .label2index    import *
from .normal2color   import *
from .onehot2index   import *
from .position2color import *
