from .adjacency               import *
from .area                    import *
from .barycenter              import *
from .barycentric_coordinates import *
from .bounding_box            import *
from .cube                    import *
from .curvature               import *
from .cylinder                import *
from .differential_operators  import *
from .disk                    import *
from .divergence              import *
from .edge_length             import *
from .equilateral_polygon     import *
from .euler_characteristic    import *
from .face2vertex             import *
from .genus                   import *
from .gradient                import *
from .grid2mesh               import *
from .hausdorff_metric        import *
from .hexahedron              import *
from .icosahedron             import *
from .klein_figure8           import *
from .laplacian               import *
from .meandering_triangle     import *
from .mesh2soup               import *
from .metric                  import *
from .mobius_strip            import *
from .normalize_scale         import *
from .octahedron              import *
from .pca                     import *
from .plane                   import *
from .point_plane_distance    import *
from .poly_corner_angles      import *
from .poly_corner_cosines     import *
from .poly_corner_cotangents  import *
from .poly_corner_normals     import *
from .poly_edges              import *
from .poly_points             import *
from .project_point_on_plane  import *
from .quad                    import *
from .shape_scale             import *
from .soup2mesh               import *
from .specular_direction      import *
from .sphere                  import *
from .sphere_coverage         import *
from .spherical_helix         import *
from .subdivide               import *
from .tetrahedron             import *
from .torus                   import *
from .triangle                import *
from .triangle_angle          import *
from .triangle_cotangent      import *
from .triangle_fan            import *
from .triangle_normal         import *
from .triangle_ratio          import *
from .unsubdivide             import *
from .vertex_normal           import *
from .vertex2face             import *

# Import with dependencies
try:
    from .mesh      import *
    from .mesh2data import *
    from .data2mesh import *
except ImportError:
    print('torch_geometric failed to be imported.\nAll dependent imports are ignored.')
