from . import size
from . import numel
from . import isempty
from . import ndim
from . import row
from . import col
from . import depth
from . import nop
from . import isint
from . import isfloat
from . import istuple
from . import islist
from . import isnone
from . import istorch
from . import isnumpy
from . import isstring
from . import strcmp
from . import strcmpi
from . import strrep
from . import swap
