function [ID] = color2index(C)
% COLOR2INDEX  Converts a color into a linear index.
%   ID = COLOR2INDEX(C) returns a nx1 vector, with ID(i) representing the
%   color C(i,:).
if(isdouble(C))
    C = color2uint8(C);
end
ID = cell2mat(...
              cellfun(@(c) typecast([c(1) c(2) c(3) uint8(0)],'uint32'),...
                      num2cell(C,ndims(C)),...
                      'UniformOutput',false)...
             );
end